<% db_socket = ENV['DEV_MYSQL_SOCKET'] || '/tmp/mysql.sock' %>

default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5

development:
  <<: *default
  username: root
  database: translations_development
  socket: <%= db_socket %>
  password:

test:
  <<: *default
  username: root
  database: translations_test
  socket: <%= db_socket %>
  password:


